variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


stages:
  - build
  - lint
  - test


build:
  stage: build
  image: registry.ubicast.net/docker/dind-compose
  services:
    - docker:dind
  tags:
    - dind
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - make build
    - make push
  interruptible: true


lint:
  stage: lint
  image: $DOCKER_IMAGE
  script:
    - make lint
  interruptible: true


test:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - make test
  coverage: '/^TOTAL .+ ([0-9]{1,3}%)$/'
  interruptible: true
